plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = "${mod_version}"
group = 'net.tierrasfantasticas.tfclient'

base {
    archivesName = "tfclient-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            args '--width', '1280', '--height', '720'
            mods {
                tfclient {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, 'tfclient.refmap.json'
    config 'tfclient.mixins.json'
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('processResources', ProcessResources).configure {
    def props = [mod_version: mod_version]
    inputs.properties props
    filesMatching('META-INF/mods.toml') {
        expand props
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title'     : 'tfclient',
            'Specification-Vendor'    : 'Tierras Fantásticas',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'Tierras Fantásticas',
            'MixinConfigs'            : 'tfclient.mixins.json'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
