modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="tfclient"
version="${mod_version}"
displayName="TF Client"
description='''Cliente oficial de Tierras Fantásticas: pantalla de carga y menú principal propios, conexión directa al servidor y mundo local.'''
logoFile="tfclient_logo.png"
authors="Tierras Fantásticas"
# Mod solo de cliente: no hace falta en el servidor.
displayTest="IGNORE_ALL_VERSION"

[[dependencies.tfclient]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.tfclient]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="CLIENT"
